services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - M://ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=120m
      - OLLAMA_LOAD_TIMEOUT=10m
      - OLLAMA_MULTIUSER_CACHE=1
#      - OLLAMA_MAX_LOADED_MODELS=3
#      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_NEW_ENGINE=1
      - OLLAMA_FLASH_ATTENTION=1
#      - OLLAMA_INTEL_GPU=1
#      - OLLAMA_CONTEXT_LENGTH=1048576
      - OLLAMA_CONTEXT_LENGTH=32768
#      - CUDA_VISIBLE_DEVICES=0,1,2
#      - OLLAMA_HOST=0.0.0.0:11434
#      - OLLAMA_KV_CACHE_TYPE=q8_0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    runtime: nvidia
    networks:
      - ai_network
    restart: unless-stopped


networks:
  ai_network:
    driver: bridge